name: Run pytest

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run tests with pytest
    runs-on: ubuntu-latest

      ENV : "dev"

      SECRET_KEY: "09d25e094faa6ca9538c818166b7a9563b93f4268f6f0f4caa6cf63b88e8d3e7"
      ALGORITHM: "HS256"
      ACCESS_TOKEN_EXPIRE_MINUTES: 60
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11' 
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests
      run: |
        pytest
